version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest ##postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: mibasededatos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
